name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_push:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build
      - name: Assemble files
        run: ./gradlew assemble
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build Docker image
        run: docker build . -t ghcr.io/tehw0lf/kotlett:$GITHUB_SHA --cache-from ghcr.io/tehw0lf/kotlett:latest
      - name: Tag Docker image
        run: docker tag ghcr.io/tehw0lf/kotlett:$GITHUB_SHA ghcr.io/tehw0lf/kotlett:latest
      - name: Publish Docker image
        run: docker push ghcr.io/tehw0lf/kotlett:$GITHUB_SHA
